title: Ting-Jui Chang
position: Ph.D. Student
affiliation: Northeastern University
email: chang.tin (at) northeastern.edu
keywords: minimal academic
google_scholar: https://scholar.google.com/citations?user=OJbToA8AAAAJ&hl=zh-TW
github_link:
linkedin: https://www.linkedin.com/in/ting-jui-chang-b73491131/
avatar: ./assets/img/avatar.png
NEULogo: ./assets/img/NEU_logo.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
