title: Ting-Jui Chang    張庭瑞
position: Ph.D. Student
affiliation: Northeastern University
email: chang.tin (at) northeastern.edu
keywords: minimal academic
google_scholar: https://scholar.google.com/citations?user=OJbToA8AAAAJ&hl=zh-TW
github_link:
linkedin: https://www.linkedin.com
avatar:
NEULogo: ./assets/img/NEU_logo.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: Ting-Jui Chang is a Ph.D. student working with Prof. Shahin Shahrampour on online optimization and distributed online control.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
