on: push
jobs:
  build:
    runs-on: ubuntu-latest
    name: script/cibuild
    steps:
      - uses: actions/checkout@v2
#       - uses: actions/setup-ruby@v1
#         with:
#           ruby-version: 2.7
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: build
        run: script/bootstrap
      - name: test
        run: script/cibuild
